version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: