version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy  # Đảm bảo MongoDB sẵn sàng trước khi chạy app
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules  # Chặn việc ghi đè node_modules trong container
    command: ["npm", "start"]  # Đảm bảo chạy đúng script trong package.json

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    healthcheck: 
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data: